source "https://rubygems.org"

ruby "3.2.0"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.5"
gem "puma", ">= 6.0"
gem "redis", "~> 5.0"
gem "sidekiq", "~> 7.2"

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
